export interface FlightFilterProduct {
  id: number;
  flightType: string;
  departureDate: Date | null;
  arrivalDate: Date | null;
  classType: string;
  priceCategory: string;
  passengerType: string;
}

export const FlightFilterProducts = [
  {
    id: 1,
    flightType: "Return",
    departureDate: new Date("2023-09-01"),
    arrivalDate: new Date("2023-09-05"),
    classType: "First Class",
    priceCategory: "Best",
    passengerType: "Adult",
  },
  {
    id: 2,
    flightType: "One Way",
    departureDate: new Date("2023-09-10"),
    arrivalDate: new Date("2023-09-12"),
    classType: "Business Class",
    priceCategory: "Cheap",
    passengerType: "Student",
  },
  {
    id: 3,
    flightType: "Multi-City",
    departureDate: new Date("2023-09-15"),
    arrivalDate: new Date("2023-09-20"),
    classType: "Economy",
    priceCategory: "Quickest",
    passengerType: "Youth",
  },
  {
    id: 4,
    flightType: "Return",
    departureDate: new Date("2023-09-08"),
    arrivalDate: new Date("2023-09-12"),
    classType: "Premium Economy",
    priceCategory: "Best",
    passengerType: "Adult",
  },
  {
    id: 5,
    flightType: "One Way",
    departureDate: new Date("2023-09-18"),
    arrivalDate: new Date("2023-09-20"),
    classType: "Business Class",
    priceCategory: "Best",
    passengerType: "Youth",
  },
  {
    id: 6,
    flightType: "Multi-City",
    departureDate: new Date("2023-09-25"),
    arrivalDate: new Date("2023-09-28"),
    classType: "Economy",
    priceCategory: "Cheap",
    passengerType: "Children",
  },
  {
    id: 7,
    flightType: "Return",
    departureDate: new Date("2023-10-05"),
    arrivalDate: new Date("2023-10-10"),
    classType: "First Class",
    priceCategory: "Quickest",
    passengerType: "Adult",
  },
  {
    id: 8,
    flightType: "One Way",
    departureDate: new Date("2023-10-15"),
    arrivalDate: new Date("2023-10-18"),
    classType: "Business Class",
    priceCategory: "Best",
    passengerType: "Student",
  },
  {
    id: 9,
    flightType: "Multi-City",
    departureDate: new Date("2023-10-22"),
    arrivalDate: new Date("2023-10-25"),
    classType: "Economy",
    priceCategory: "Cheap",
    passengerType: "Youth",
  },
  {
    id: 10,
    flightType: "Return",
    departureDate: new Date("2023-10-28"),
    arrivalDate: new Date("2023-11-02"),
    classType: "Premium Economy",
    priceCategory: "Best",
    passengerType: "Adult",
  },
  {
    id: 11,
    flightType: "One Way",
    departureDate: new Date("2023-11-07"),
    arrivalDate: new Date("2023-11-10"),
    classType: "Business Class",
    priceCategory: "Quickest",
    passengerType: "Student",
  },
  {
    id: 12,
    flightType: "Multi-City",
    departureDate: new Date("2023-11-15"),
    arrivalDate: new Date("2023-11-18"),
    classType: "Economy",
    priceCategory: "Cheap",
    passengerType: "Youth",
  },
  {
    id: 13,
    flightType: "Return",
    departureDate: new Date("2023-11-25"),
    arrivalDate: new Date("2023-11-30"),
    classType: "First Class",
    priceCategory: "Best",
    passengerType: "Adult",
  },
  {
    id: 14,
    flightType: "One Way",
    departureDate: new Date("2023-12-05"),
    arrivalDate: new Date("2023-12-08"),
    classType: "Business Class",
    priceCategory: "Cheap",
    passengerType: "Student",
  },
  {
    id: 15,
    flightType: "Multi-City",
    departureDate: new Date("2023-12-15"),
    arrivalDate: new Date("2023-12-20"),
    classType: "Economy",
    priceCategory: "Quickest",
    passengerType: "Youth",
  },
  {
    id: 16,
    flightType: "Return",
    departureDate: new Date("2023-12-25"),
    arrivalDate: new Date("2023-12-30"),
    classType: "Premium Economy",
    priceCategory: "Best",
    passengerType: "Adult",
  },
  {
    id: 17,
    flightType: "One Way",
    departureDate: new Date("2024-01-05"),
    arrivalDate: new Date("2024-01-08"),
    classType: "Business Class",
    priceCategory: "Best",
    passengerType: "Youth",
  },
  {
    id: 18,
    flightType: "Multi-City",
    departureDate: new Date("2024-01-15"),
    arrivalDate: new Date("2024-01-20"),
    classType: "Economy",
    priceCategory: "Cheap",
    passengerType: "Children",
  },
  {
    id: 19,
    flightType: "Return",
    departureDate: new Date("2024-01-25"),
    arrivalDate: new Date("2024-01-30"),
    classType: "First Class",
    priceCategory: "Quickest",
    passengerType: "Adult",
  },
  {
    id: 20,
    flightType: "One Way",
    departureDate: new Date("2024-02-05"),
    arrivalDate: new Date("2024-02-08"),
    classType: "Business Class",
    priceCategory: "Best",
    passengerType: "Student",
  },
];
