export interface FlightFilterProduct {
  id: number;
  flightType: string;
  departureDate: Date | null;
  arrivalDate: Date | null;
  departureCity: string;
  arrivalCity: string;
  classType: string;
  priceCategory: string;
  passengerType: string;
  flightName: string;
  flightLogo: string;
  departureTime: string;
  arrivalTime: string;
  flightPrice: number;
}

export const FlightFilterProducts: FlightFilterProduct[] = [
  {
    id: 1,
    flightType: "Return",
    departureDate: new Date("2023-09-01"),
    arrivalDate: new Date("2023-09-05"),
    departureCity: "New York",
    arrivalCity: "Los Angeles",
    classType: "First",
    priceCategory: "Best",
    passengerType: "Adult",
    flightName: "Royal Air Maroc",
    flightLogo: "flight-logo-1.png",
    departureTime: "22:10",
    arrivalTime: "20:30",
    flightPrice: 4129,
  },
  {
    id: 2,
    flightType: "One Way",
    departureDate: new Date("2023-09-10"),
    arrivalDate: new Date("2023-09-12"),
    departureCity: "Chicago",
    arrivalCity: "Miami",
    classType: "Business",
    priceCategory: "Cheap",
    passengerType: "Student",
    flightName: "Example Airlines",
    flightLogo: "flight-logo-2.png",
    departureTime: "18:45",
    arrivalTime: "23:30",
    flightPrice: 2850,
  },
  {
    id: 3,
    flightType: "Multi-City",
    departureDate: new Date("2023-09-15"),
    arrivalDate: new Date("2023-09-20"),
    departureCity: "Los Angeles",
    arrivalCity: "Chicago",
    classType: "Economy",
    priceCategory: "Quickest",
    passengerType: "Youth",
    flightName: "FlyNow Airlines",
    flightLogo: "flight-logo-3.png",
    departureTime: "11:20",
    arrivalTime: "17:10",
    flightPrice: 1375,
  },
  {
    id: 4,
    flightType: "Return",
    departureDate: new Date("2023-09-08"),
    arrivalDate: new Date("2023-09-12"),
    departureCity: "Miami",
    arrivalCity: "New York",
    classType: "Premium Economy",
    priceCategory: "Best",
    passengerType: "Adult",
    flightName: "SkyJet Airways",
    flightLogo: "flight-logo-4.png",
    departureTime: "14:30",
    arrivalTime: "22:15",
    flightPrice: 3250,
  },
  {
    id: 5,
    flightType: "One Way",
    departureDate: new Date("2023-09-18"),
    arrivalDate: new Date("2023-09-20"),
    departureCity: "Los Angeles",
    arrivalCity: "San Francisco",
    classType: "Business",
    priceCategory: "Best",
    passengerType: "Youth",
    flightName: "Wings Express",
    flightLogo: "flight-logo-5.png",
    departureTime: "09:45",
    arrivalTime: "11:30",
    flightPrice: 2150,
  },
  {
    id: 6,
    flightType: "Multi-City",
    departureDate: new Date("2023-09-25"),
    arrivalDate: new Date("2023-09-28"),
    departureCity: "New York",
    arrivalCity: "Chicago",
    classType: "Economy",
    priceCategory: "Cheap",
    passengerType: "Children",
    flightName: "Air Globe",
    flightLogo: "flight-logo-6.png",
    departureTime: "07:20",
    arrivalTime: "11:10",
    flightPrice: 950,
  },
  {
    id: 7,
    flightType: "Return",
    departureDate: new Date("2023-10-05"),
    arrivalDate: new Date("2023-10-10"),
    departureCity: "Los Angeles",
    arrivalCity: "Miami",
    classType: "First",
    priceCategory: "Quickest",
    passengerType: "Adult",
    flightName: "Global Wings",
    flightLogo: "flight-logo-7.png",
    departureTime: "16:15",
    arrivalTime: "23:45",
    flightPrice: 4890,
  },
  {
    id: 8,
    flightType: "One Way",
    departureDate: new Date("2023-10-15"),
    arrivalDate: new Date("2023-10-18"),
    departureCity: "Chicago",
    arrivalCity: "New York",
    classType: "Business",
    priceCategory: "Best",
    passengerType: "Student",
    flightName: "StarFlight",
    flightLogo: "flight-logo-8.png",
    departureTime: "09:30",
    arrivalTime: "11:15",
    flightPrice: 2100,
  },
  {
    id: 9,
    flightType: "Multi-City",
    departureDate: new Date("2023-10-22"),
    arrivalDate: new Date("2023-10-25"),
    departureCity: "Miami",
    arrivalCity: "Los Angeles",
    classType: "Economy",
    priceCategory: "Cheap",
    passengerType: "Youth",
    flightName: "Skylink Airlines",
    flightLogo: "flight-logo-9.png",
    departureTime: "14:40",
    arrivalTime: "20:20",
    flightPrice: 1525,
  },
  {
    id: 10,
    flightType: "Return",
    departureDate: new Date("2023-10-28"),
    arrivalDate: new Date("2023-11-02"),
    departureCity: "Los Angeles",
    arrivalCity: "New York",
    classType: "Premium Economy",
    priceCategory: "Best",
    passengerType: "Adult",
    flightName: "Wingsoar",
    flightLogo: "flight-logo-10.png",
    departureTime: "12:20",
    arrivalTime: "21:45",
    flightPrice: 3799,
  },
  {
    id: 21,
    flightType: "Return",
    departureDate: new Date("2024-02-15"),
    arrivalDate: new Date("2024-02-18"),
    departureCity: "Miami",
    arrivalCity: "Chicago",
    classType: "First",
    priceCategory: "Quickest",
    passengerType: "Adult",
    flightName: "AeroLux Airlines",
    flightLogo: "flight-logo-21.png",
    departureTime: "08:45",
    arrivalTime: "11:30",
    flightPrice: 3180,
  },
  {
    id: 22,
    flightType: "One Way",
    departureDate: new Date("2024-02-25"),
    arrivalDate: new Date("2024-02-28"),
    departureCity: "Los Angeles",
    arrivalCity: "San Francisco",
    classType: "Business",
    priceCategory: "Best",
    passengerType: "Student",
    flightName: "FlyHigh Airways",
    flightLogo: "flight-logo-22.png",
    departureTime: "13:20",
    arrivalTime: "15:15",
    flightPrice: 1890,
  },
  {
    id: 23,
    flightType: "Multi-City",
    departureDate: new Date("2024-03-05"),
    arrivalDate: new Date("2024-03-10"),
    departureCity: "Chicago",
    arrivalCity: "Miami",
    classType: "Economy",
    priceCategory: "Cheap",
    passengerType: "Youth",
    flightName: "AirWings Express",
    flightLogo: "flight-logo-23.png",
    departureTime: "09:40",
    arrivalTime: "12:25",
    flightPrice: 1035,
  },
  {
    id: 24,
    flightType: "Return",
    departureDate: new Date("2024-03-15"),
    arrivalDate: new Date("2024-03-20"),
    departureCity: "Los Angeles",
    arrivalCity: "New York",
    classType: "Premium Economy",
    priceCategory: "Best",
    passengerType: "Adult",
    flightName: "Skyline Airlines",
    flightLogo: "flight-logo-24.png",
    departureTime: "17:10",
    arrivalTime: "22:40",
    flightPrice: 2675,
  },
  {
    id: 25,
    flightType: "One Way",
    departureDate: new Date("2024-03-25"),
    arrivalDate: new Date("2024-03-28"),
    departureCity: "Chicago",
    arrivalCity: "Miami",
    classType: "Business",
    priceCategory: "Quickest",
    passengerType: "Student",
    flightName: "JetStream Airways",
    flightLogo: "flight-logo-25.png",
    departureTime: "10:15",
    arrivalTime: "12:00",
    flightPrice: 1790,
  },
  {
    id: 26,
    flightType: "Multi-City",
    departureDate: new Date("2024-04-05"),
    arrivalDate: new Date("2024-04-10"),
    departureCity: "Los Angeles",
    arrivalCity: "San Francisco",
    classType: "Economy",
    priceCategory: "Cheap",
    passengerType: "Youth",
    flightName: "FlyEasy Airlines",
    flightLogo: "flight-logo-26.png",
    departureTime: "09:30",
    arrivalTime: "11:20",
    flightPrice: 850,
  },
  {
    id: 27,
    flightType: "Return",
    departureDate: new Date("2024-04-15"),
    arrivalDate: new Date("2024-04-20"),
    departureCity: "Miami",
    arrivalCity: "New York",
    classType: "Premium Economy",
    priceCategory: "Best",
    passengerType: "Adult",
    flightName: "Cloud9 Airways",
    flightLogo: "flight-logo-27.png",
    departureTime: "14:00",
    arrivalTime: "19:30",
    flightPrice: 2350,
  },
  {
    id: 28,
    flightType: "One Way",
    departureDate: new Date("2024-04-25"),
    arrivalDate: new Date("2024-04-28"),
    departureCity: "Chicago",
    arrivalCity: "Miami",
    classType: "Business",
    priceCategory: "Quickest",
    passengerType: "Student",
    flightName: "Horizon Air",
    flightLogo: "flight-logo-28.png",
    departureTime: "11:45",
    arrivalTime: "13:30",
    flightPrice: 1890,
  },
];
